# torrox- HYDRA - STREET LIGHTING DASHBOARD CONFIGURATION FILE

baseURL: http://url:port

# debugAccessToken:

# Logging configuration parameters
logging:
  # Level options: INFO|ERROR|DEBUG. Default: INFO
  level: DEBUG
  # Output options: console|file. Default: console
  output: file

# PostgreSQL configuration parameters
pgsql:
  host: postgis
  user: xxxxx
  password: xxxxx
  database: xxxxx
  port: 5432

# CartoDB configuration parameters
cartodb:
  apiKey: xxxxxxxxxxxxxxxxxxxxxx
  user: xxxxxxxxxxxxx
  active: false
  enterprise: true

# urbo-processing parameters
processing:
  active: false
  url: http://localhost:XXXX
  requestAttempts: 5
  psqlJob: connectorPsql
  cartoJob: connectorCarto
  jobAttempts: 3
  priority: critical

# Orion Context Broker API URLs
contextBrokerUrls:
  portAuthtk: xxxxxxxxxxxxx
  portCtxApi: xxxxxxxxx
  urlCtxBrBase: https://xxxxxxxxxxxxxxxxxxxxxxxx

# Fiware subservices subscriptions configuration
subservices:
  - id: lighting
    service: XXX
    subservice: /and_sr_lucena
    auth:
      user: XXX
      password: XXX

subscriptions:
  ###StreetlightControlCabinet ######################
  - id: lighting_stcabinet
    subservice_id: lighting
    schemaname: torrox
    subsduration: P8M
    substhrottling: PT0S
    fetchDataOnCreated: false
    entityTypes:
      - typeName: ht_6
    mode: append
    attributes:
      - name: position
        type: coords
        cartodb: true
      - name: timeInstant
        namedb: TimeInstant
        type: ISO8601
        indexdb: true
        cartodb: true
        constraint: true
      - name: customerId
        namedb: customerid
        type: string
        cartodb: true
      - name: premisesId
        namedb: premisesid
        type: string
        cartodb: true
      - name: groupId
        namedb: groupid
        type: string
        cartodb: true
      - name: deviceType
        namedb: devicetype
        type: string
        cartodb: true
      - name: energyType
        namedb: energytype
        type: string
        cartodb: true
      - name: energyUse
        namedb: energyuse
        type: string
        cartodb: true

    trigger_attributes:
      - position
      - customerId
      - premisesId
      - groupId
      - deviceType
      - energyType
      - energyUse

  - id: lighting_stcabinet_lastdata
    subservice_id: lighting
    schemaname: torrox
    subsduration: P8M
    substhrottling: PT0S
    fetchDataOnCreated: false
    entityTypes:
      - typeName: ht_6
    mode: update
    attributes:
      - name: position
        type: coords
        cartodb: true
      - name: timeInstant
        namedb: TimeInstant
        type: ISO8601
        indexdb: true
        cartodb: true
        constraint: true
      - name: ENERGIA:ConsumoModBusenergiaacumuladaactiva
        namedb: energyconsumed
        type: float
        cartodb: true
      - name: ENERGIA:ConsumoModBusenergiaacumuladareactiva
        namedb: reactiveenergyconsumed
        type: float
        cartodb: true
      - name: ENERGIA:ConsumoactivoinstantaneoR+S+T
        namedb: totalactivepower
        type: float
        cartodb: true
      - name: ACTUACION:EncendidoconSeguridad2ONOFF
        namedb: powerstate_general
        type: string
        cartodb: true
      - name: ACTUACION:EncendidoconSeguridadONOFF
        namedb: powerstate_reduced
        type: string
        cartodb: true
      - name: customerId
        namedb: customerid
        type: string
        cartodb: true
      - name: premisesId
        namedb: premisesid
        type: string
        cartodb: true
      - name: groupId
        namedb: groupid
        type: string
        cartodb: true
      - name: deviceType
        namedb: devicetype
        type: string
        cartodb: true
      - name: energyType
        namedb: energytype
        type: string
        cartodb: true
      - name: energyUse
        namedb: energyuse
        type: string
        cartodb: true

    trigger_attributes:
      - timeInstant

  # StreetlightControlCabinet ######################
  - id: lighting_stcabinet_state
    subservice_id: lighting
    schemaname: torrox
    subsduration: P8M
    substhrottling: PT0S
    fetchDataOnCreated: false
    entityTypes:
      - typeName: ht_6
    mode: append
    attributes:
      - name: timeInstant
        namedb: "TimeInstant"
        type: ISO8601
        indexdb: true
        cartodb: true
        constraint: true
      - name: ENERGIA:ConsumoModBusenergiaacumuladaactiva
        namedb: energyconsumed
        type: float
        cartodb: true
      - name: ENERGIA:ConsumoModBusenergiaacumuladareactiva
        namedb: reactiveenergyconsumed
        type: float
        cartodb: true
      - name: ENERGIA:ConsumoactivoinstantaneoR+S+T
        namedb: totalactivepower
        type: float
        cartodb: true

    trigger_attributes:
      - ENERGIA:ConsumoModBusenergiaacumuladaactiva
      - ENERGIA:ConsumoModBusenergiaacumuladareactiva
      - ENERGIA:ConsumoactivoinstantaneoR+S+T


  # StreetlightControlCabinet ######################
  - id: lighting_stcabinet_powerstate
    subservice_id: lighting
    schemaname: torrox
    subsduration: P8M
    substhrottling: PT0S
    fetchDataOnCreated: false
    entityTypes:
      - typeName: ht_6
    mode: append
    attributes:
      - name: timeInstant
        namedb: TimeInstant
        type: ISO8601
        indexdb: true
        cartodb: true
        constraint: true
      - name: ACTUACION:EncendidoconSeguridad2ONOFF
        namedb: powerstate_general
        type: string
        cartodb: true
      - name: ACTUACION:EncendidoconSeguridadONOFF
        namedb: powerstate_reduced
        type: string
        cartodb: true

    trigger_attributes:
      - ACTUACION:EncendidoconSeguridad2ONOFF
      - ACTUACION:EncendidoconSeguridadONOFF
