baseURL: http://url:port

# debugAccessToken:

# Logging configuration parameters
logging:
  # Options: ALL | TRACE | DEBUG | INFO | WARN | ERROR | FATAL | OFF. Default: INFO.
  level: INFO
  # Options: console | file | dailyRotatingFile | sizeRotatingFile. Default: console.
  output: dailyRotatingFile
  # Configure the log file.
  file:
    # Default: `./logs`
    dir: ./logs
    # Default: `the_log`.
    name: mobility
    # File size in MB for `sizeRotatingFile` log type. Default: 20 MB.
    maxSize: 20
    # Number of old files to keep for `sizeRotatingFile` log type. Default: 5.
    oldFiles: 5
    # Boolean. If true, it'll create a separate file for errors. Default: false.
    separateError: true
  # Configure the access log. If its level is inferior than the main level it won't be logged.
  # Documentaiton: https://github.com/nomiddlename/log4js-node/wiki/Connect-Logger
  access:
    # Options: Same as the main level. Default: The one used in the main level.
    level: INFO
    # Optional. For using log4js default format: false.
    format: false
    # Optional array: each element it's like a regex. Default: empty.
    nolog:
      - ^/subscriptions/transport_vehicle

# PostgreSQL configuration parameters
pgsql:
  host: xxxxxxxx
  user: xxxxxxxx
  password: xxxxxxxx
  database: xxxxxxxx
  port: xxxxxxxx

# CartoDB configuration parameters
cartodb:
  apiKey: xxxxxxxx
  user: xxxxxxxx
  active: true
  enterprise: false
# URBO - Waste -  DEMO DASHBOARD CONFIGURATION FILE

# urbo-processing parameters
processing:
  active: false
  url: http://217.172.12.177:1026/job
  requestAttempts: 5
  psqlJob: connectorPsql
  cartoJob: connectorCarto
  jobAttempts: 3
  priority: critical

# Orion Context Broker API URLs
contextBrokerUrls:
#  portAuthtk: 1025
  portCtxApi: 1026
  urlCtxBrBase: http://217.172.12.177

# Fiware subservices subscriptions configuration
subservices:
  - id: madrid
    service: madrid
    subservice: /analytics_kpis
    auth:
      user: xxxxxxxx
      password: xxxxxxxx

subscriptions:
  - id: mobility
    subservice_id: madrid
    schemaname: madrid_mobility
    fetchDataOnCreated: true
    entityTypes:
      - typeName: TrafficFlowObserved
    mode: append
    attributes:
      - name: address
        type: json
        cartodb: false
      - name: refRoadSegment
        type: integer
        cartodb: false
      - name: congested
        type: boolean
        cartodb: false
      - name: dateModified
        type: ISO8601
        cartodb: false
      - name: dateObserved
        type: ISO8601
        cartodb: false
      - name: intensity
        type: integer
        cartodb: false
      - name: location
        type: geojson-point
        cartodb: false
      - name: name
        type: string
        cartodb: false
      - name: occupancy
        type: integer
        cartodb: false