# GUADALAJARA DEMO DASHBOARD CONFIGURATION FILE

baseURL: http://url:port

# debugAccessToken:

# Logging configuration parameters
logging:
  # Level options: INFO|ERROR|DEBUG. Default: INFO
  level: DEBUG
  # Output options: console|file. Default: console
  output: file

# PostgreSQL configuration parameters
pgsql:
  host: postgis
  user: xxxxx
  password: xxxxx
  database: xxxxx
  port: 5432

# CartoDB configuration parameters
cartodb:
  apiKey: xxxxxxxxxxxxxxxxxxxxxx
  user: xxxxxxxxxxxxx
  active: false
  enterprise: true

# urbo-processing parameters
processing:
  active: false
  url: http://localhost:XXXX
  requestAttempts: 5
  psqlJob: connectorPsql
  cartoJob: connectorCarto
  jobAttempts: 3
  priority: critical

# Orion Context Broker API URLs
contextBrokerUrls:
  portAuthtk: xxxxxxxxxxxxx
  portCtxApi: xxxxxxxxx
  urlCtxBrBase: https://xxxxxxxxxxxxxxxxxxxxxxxx

# Fiware subservices subscriptions configuration
subservices:
  - id: guadalajara_moba
    service: sc_guadalajara
    subservice: /moba
    auth:
      user: XXX
      password: XXX

  - id: guadalajara_mtc
    service: XXX
    subservice: /mtc
    auth:
      user: XXX
      password: XXX

subscriptions:
  - id: guadal_contenedores
    subservice_id: guadalajara_moba
    schemaname: guadalajara
    entityTypes:
      - typeName: MOBA
        typePattern: MOBA_[23][0-9][0-9]
    mode: insert
    attributes:
      - name: position
        type: coords
        cartodb: true
      - name: datetime
        namedb: TimeInstant
        type: ISO8601
        cartodb: true
      - name: level
        type: float
        cartodb: true
      - name: s_class
        type: string
        cartodb: true
      - name: sensorCode
        type: float
        cartodb: true
    trigger_attributes:
      - datetime
      - level
      - s_class
      - sensorCode

  - id: issue
    subservice_id: guadalajara_mtc
    schemaname: guadalajara
    entityTypes:
      - typeName: SNIncidence
    mode: insert
    attributes:
      - name: longitude
        type: float
        cartodb: true
      - name: latitude
        type: float
        cartodb: true
      - name: incidenceCode
        namedb: incidence_code
        type: string
        cartodb: true
      - name: category
        type: string
        cartodb: true
      - name: status_datetime
        namedb: TimeInstant
        type: ISO8601
        cartodb: true
      - name: priority
        type: integer
        cartodb: true
      - name: jurisdiction
        type: string
        cartodb: true
      - name: status
        type: string
        cartodb: true
      - name: subject
        type: string
        cartodb: true
    trigger_attributes:
      - status_datetime
      - status
      - category
      - priority
