# GUADALAJARA DEMO DASHBOARD CONFIGURATION FILE

baseURL: http://urbo-backend-dev.geographica.gs/connector/guadalajara

# debugAccessToken:

# Logging configuration parameters
logging:
  # Level options: INFO|ERROR|DEBUG. Default: INFO
  level: DEBUG
  # Output options: console|file. Default: console
  output: file

# PostgreSQL configuration parameters
pgsql:
  host: xxxxxx
  user: xxxx
  password: xxxx
  database: xxxx
  port: xxxx

# CartoDB configuration parameters
cartodb:
  apiKey: xxxxxxxx
  user: xxxxxxxx
  active: true
  enterprise: true

# urbo-processing parameters
processing:
  active: true
  url: xxxxxxxxxx
  requestAttempts: 5
  psqlJob: connectorPsql
  cartoJob: connectorCarto
  jobAttempts: 3
  priority: critical

# Orion Context Broker API URLs
contextBrokerUrls:
  portAuthtk: xxx
  portCtxApi: xxxx
  urlCtxBrBase: xxxxxxxxxxxxxxxxxx

# Fiware subservices subscriptions configuration
subservices:
  - id: guadalajara_moba
    service: xxxxxxxxxxxxxxx
    subservice: /xxxxxxxx
    auth:
      user: xxxxxxxxxx
      password: xxxxxxxxx

  - id: guadalajara_mtc
    service: xxxxxxxxxx
    subservice: /xxxxxxxxxx
    auth:
      user: xxxxxxxxxxxxxx
      password: xxxxxxxxxxxxx

subscriptions:
  - id: contenedores
    subservice_id: guadalajara_moba
    schemaname: guadalajara
    entityTypes:
      - typeName: MOBA
    mode: append
    attributes:
      #- name: position
      #  type: coords
      #  cartodb: true
      - name: datetime
        namedb: TimeInstant
        type: ISO8601
        cartodb: true
      - name: level
        type: float
        cartodb: true
      #- name: s_class
      #  type: string
      #  cartodb: true
      #- name: sensorCode
      #  type: float
      #  cartodb: true
      #  namedb: sensor_code
    trigger_attributes:
      - datetime
      - level
      #- s_class
      #- sensorCode

  - id: contenedores_lastdata
    subservice_id: guadalajara_moba
    schemaname: guadalajara
    entityTypes:
      - typeName: MOBA
    mode: update
    attributes:
      - name: position
        type: coords
        cartodb: true
      - name: datetime
        namedb: TimeInstant
        type: ISO8601
        cartodb: true
      - name: level
        type: float
        cartodb: true
      - name: s_class
        type: string
        cartodb: true
      - name: sensorCode
        type: float
        cartodb: true
        namedb: sensor_code

    trigger_attributes:
      - datetime
      - level
      - s_class
      - sensorCode

  - id: issue
    subservice_id: guadalajara_mtc
    schemaname: guadalajara
    entityTypes:
      - typeName: SNIncidence
    mode: append
    attributes:
      - name: longitude
        namedb: lon
        type: coords
        cartodb: true
      - name: latitude
        namedb: lat
        type: coords
        cartodb: true
      - name: incidenceCode
        namedb: incidence_code
        type: string
        cartodb: true
      - name: category
        type: string
        cartodb: true
      - name: status_datetime
        namedb: TimeInstant
        type: ISO8601
        cartodb: true
      - name: priority
        type: integer
        cartodb: true
      - name: jurisdiction
        type: string
        cartodb: true
      - name: status
        type: string
        cartodb: true
      - name: subject
        type: string
        cartodb: true
    trigger_attributes:
      - status_datetime
      - status
      - category
      - priority
