# FIWARE-PGSQL/CartoDB CONNECTOR CONFIGURATION FILE

# BASE URL
baseURL: http://url:port

# Logging configuration parameters
logging:
  # Level options: INFO|ERROR|DEBUG. Default: INFO
  level: INFO
  # Output options: console|file. Default: console
  output: console

# PostgreSQL configuration parameters
pgsql:
  host: XXX
  user: XXX
  password: XXX
  database: XXX
  port: XXX

# CartoDB configuration parameters
cartodb:
  apiKey: XXX
  user: XXX
  active: true
  # Optional. Default to false. If you've an enterprise account at CartoDB you must set this param to true
  enterprise: false

# Orion Context Broker API URLs
contextBrokerUrls:
  portAuthtk: XXXXX
  portCtxApi: XXXXX
  urlCtxBrBase: https://url

# Fiware subservices catalog.
subservices:
    # Internal id of subservice. It must be a string without spaces or special characters. Only [a-z][A-Z]
  - id: id_subservice
    # Fiware service name
    service: XXX
    # Fiware subservice name (slash must be added)
    subservice: /XXX
    # Credentiales
    auth:
      user: XXX
      password: XXX

# List of subscriptions
subscriptions:
    # Mandatory: Internal ID for the subscription
  - id: subscription_id
    # Mandatory: ID of subservice at subservices catalog.
    subservice_id: id_subservice
    # Mandatory: schema to store data.
    schema: schemaname
    # Fiware entities to be subscribed.
    # Mandatory: typeName - entity types
    # Optional: typePattern - custom regular expressions to get entitites. Default pattern (get all entities from type): .*
    entityTypes:
      - typeName: type
        typePattern: .*
    # Optional: Table name for PGSQL and CartoDB. If not provided default to ID.
    tablename: subscription_id
    # Optional: Subscription mode. Posible values are append|update. Default: append
    mode: append
    # List of attributes. These are the attributes of the subscription and how they're mapped into the PostgreSQL database and CartoDB
    attributes:
      - # Attribute name (Fiware attribute name)
        name: name
        # Database attribute name (If it does not exist "name" is used)
        namedb: name
        # Mandatory: Type of attribute: Currently supported: 'coords','string','float','integer','ISO8601|timestamp'. Todo: geojson.
        type: string
        # Optional. Default to false. If set to true, the attribute will be synced at CartoDB
        cartodb: true
        # Optional. Default to false. If true a index will be created at PostgreSQL.
        index: true
      - name: position
        type: coords
        cartodb: true
      - name: timeinstant
        type: ISO8601
      - name: valor_01
        type: string
    # Mandatory: List of trigger attributes. A notification will be sent by Context Broker when the value of one of the following attributes change.
    trigger_attributes:
      - timeinstant
