  # FIWARE URBO STREETLIGHT CONNECTOR CONFIGURATION FILE

baseURL: http://url:port

# debugAccessToken:

# Logging configuration parameters
logging:
  # Level options: INFO|ERROR|DEBUG. Default: INFO
  level: DEBUG
  # Output options: console|file. Default: console
  output: file

# PostgreSQL configuration parameters
pgsql:
  host: postgis
  user: xxxxxxxxxx
  password: xxxxxxxxxx
  database: xxxxxxxxxx
  port: 5432

# CartoDB configuration parameters
cartodb:
  apiKey: xxxxxxxxxx
  user: xxxxxxxxxx
  active: false
  enterprise: true

# urbo-processing parameters
processing:
  active: false
  url: http://localhost:XXXX
  requestAttempts: 5
  psqlJob: connectorPsql
  cartoJob: connectorCarto
  jobAttempts: 3
  priority: critical

# Orion Context Broker API URLs
contextBrokerUrls:
  portAuthtk: xxxxxxxxxx
  portCtxApi: xxxxxxxxxx
  urlCtxBrBase: https://xxxxxxxxxx

# Fiware subservices subscriptions configuration
subservices:
  - id: streetlight_simulations
    service: urbo
    subservice: /geographica
    auth:
      user: xxxxxxxxxx
      password: xxxxxxxxxx

subscriptions:
  # StreetlightControlCabinet ######################
  - id: lighting_stcabinet
    subservice_id: lighting_simulations
    schemaname: distrito_telefonica
    subsduration: P8M
    substhrottling: PT0S
    fetchDataOnCreated: false
    entityTypes:
      - typeName: StreetlightControlCabinet
    mode: append
    attributes:
      - name: position
        type: geojson-point
        cartodb: true
      - name: TimeInstant
        type: ISO8601
        indexdb: true
        cartodb: true
        constraint: true
      - name: areaServed
        namedb: areaserved
        type: string
        cartodb: true
      - name: cupboardMadeOf
        namedb: cupboardmadeof
        type: string
        cartodb: true
      - name: brandName
        namedb: brandname
        type: string
        cartodb: true
      - name: modelName
        namedb: modelname
        type: string
        cartodb: true
      - name: workingMode
        namedb: workingmode
        type: string
        cartodb: true
      - name: maximumPowerAvailable
        namedb: maximumpoweravailable
        type: integer
        cartodb: true
      - name: customerId
        namedb: customerid
        type: string
        cartodb: true
      - name: premisesId
        namedb: premisesid
        type: string
        cartodb: true
      - name: groupId
        namedb: groupid
        type: string
        cartodb: true
      - name: deviceType
        namedb: devicetype
        type: string
        cartodb: true
      - name: energyType
        namedb: energytype
        type: string
        cartodb: true
      - name: energyUse
        namedb: energyuse
        type: string
        cartodb: true

    trigger_attributes:
      - position
      - areaServed
      - cupboardMadeOf
      - brandName
      - modelName
      - workingMode
      - maximumPowerAvailable
      - customerId
      - premisesId
      - groupId
      - deviceType
      - energyType
      - energyUse

  - id: lighting_stcabinet_lastdata
    subservice_id: lighting_simulations
    schemaname: distrito_telefonica
    subsduration: P8M
    substhrottling: PT0S
    fetchDataOnCreated: false
    entityTypes:
      - typeName: StreetlightControlCabinet
    mode: update
    attributes:
      - name: position
        type: geojson-point
        cartodb: true
      - name: TimeInstant
        type: ISO8601
        indexdb: true
        cartodb: true
        constraint: true
      - name: areaServed
        namedb: areaserved
        type: string
        cartodb: true
      - name: cupboardMadeOf
        namedb: cupboardmadeof
        type: string
        cartodb: true
      - name: brandName
        namedb: brandname
        type: string
        cartodb: true
      - name: modelName
        namedb: modelname
        type: string
        cartodb: true
      - name: workingMode
        namedb: workingmode
        type: string
        cartodb: true
      - name: maximumPowerAvailable
        namedb: maximumpoweravailable
        type: integer
        cartodb: true
      - name: ___Consumo_ModBus__energía_acumulada_activa_
        namedb: energyconsumed
        type: long integer
        cartodb: true
      - name: ___Consumo_ModBus__energía_acumulada_reactiva_
        namedb: reactiveenergyconsumed
        type: long integer
        cartodb: true
      - name: ___Consumo_activo_instantáneo__R+S+T_
        namedb: totalactivepower
        type: integer
        cartodb: true
      - name: customerId
        namedb: customerid
        type: string
        cartodb: true
      - name: premisesId
        namedb: premisesid
        type: string
        cartodb: true
      - name: groupId
        namedb: groupid
        type: string
        cartodb: true
      - name: deviceType
        namedb: devicetype
        type: string
        cartodb: true
      - name: energyType
        namedb: energytype
        type: string
        cartodb: true
      - name: energyUse
        namedb: energyuse
        type: string
        cartodb: true

    trigger_attributes:
      - TimeInstant

  # StreetlightControlCabinet ######################
  - id: lighting_stcabinet_state
    subservice_id: lighting_simulations
    schemaname: distrito_telefonica
    subsduration: P8M
    substhrottling: PT0S
    fetchDataOnCreated: false
    entityTypes:
      - typeName: StreetlightControlCabinet
    mode: append
    attributes:
      - name: TimeInstant
        type: ISO8601
        indexdb: true
        cartodb: true
        constraint: true
      - name: ___Consumo_ModBus__energía_acumulada_activa_
        namedb: energyconsumed
        type: long integer
        cartodb: true
      - name: ___Consumo_ModBus__energía_acumulada_reactiva_
        namedb: reactiveenergyconsumed
        type: long integer
        cartodb: true
      - name: ___Consumo_activo_instantáneo__R+S+T_
        namedb: totalactivepower
        type: integer
        cartodb: true

    trigger_attributes:
      - ___Consumo_activo_instantáneo__R+S+T_


  # StreetlightControlCabinet ######################
  - id: lighting_stcabinet_powerstate
    subservice_id: lighting_simulations
    schemaname: distrito_telefonica
    subsduration: P8M
    substhrottling: PT0S
    fetchDataOnCreated: false
    entityTypes:
      - typeName: StreetlightControlCabinet
    mode: append
    attributes:
      - name: TimeInstant
        type: ISO8601
        indexdb: true
        cartodb: true
        constraint: true
      - name: powerState
        namedb: powerstate
        type: string
    trigger_attributes:
      - powerState
