# Git HUB project: https://github.com/nodejs/docker-node/blob/04df8682a438b0ced8f530ab562f5197595e0cbb/4.2/onbuild/Dockerfile
# Docker Hub: https://hub.docker.com/_/node/
FROM node:4-onbuild

RUN npm install -g nodemon

EXPOSE 3000